<head>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  <script src="assets/js/login.js"></script>
  <link rel="stylesheet" href="assets/css/login.css" type="text/css"/>
</head>
<section class="col-l-4">
</section>
<section class="col-l-4">
  <h1>Login</h1>

  <form method="post">
    <label for='username'><b>Nome utente:</b></label><br />
    <div class="input-container">
      <i class="fa fa-user icon"></i>
      <input class="textform" id="username" type="text" name="username" />
    </div>
    <label class='checkerLabel' id="usernamelabel">Questo nome utente non esiste</label><br /><br />
    <label for='password'><b>Password:</b></label><br />
    <div class="input-container">
      <i class="fa fa-key icon"></i>
      <input type="password" id="password" name="password" /><br /><br>
    </div>
    <input id="submitBtn" class="standardBtn" type="submit" value="Login" disabled/>
  </form><br><br>
  <p>Se non hai un account, <a class="link1" href="register">registrati ora</a>.</p>
</section>
<section class="col-l-4">
</section>
